### ISSUE TITLE
One-step GitHub Actions integration for GCP

### ISSUE THREAD

**Issue by imjasonh** [imjasonh/ideas#129]
Most recently inspired by https://x.com/jessfraz/status/1817618262706073921

```
on:
  push:
  pull_request_target: # see below*

permissions:
  contents: read
  id-token: write

jobs:
  - name: build
    steps:
      - uses: whatever/gcp-monitoring@v0
        with:
          project: <project>
      - uses: actions/checkout@v5
      - run: # do stuff
```

Including this action would:
- collect all logs and send them to Cloud Logging
- emit traces to Cloud Trace
- emit metrics to Cloud Monitoring
  - repo, workflow, job

A pre-action would set up the collector(s), a post-action would block until they're flushed.

Define a standard service account name (github@<project>.iam.gserviceaccount.com) which is assumed to have the necessary permissions.

Provide a script and/or TF to create the SA and give it the necessary permissions, and bind it to the GH OIDC identity for the org/repo/workflow/branch.

\*ID tokens aren't available in `pull_request` workflows, which makes this kind of annoying. But it would work easily for `push` and ehh `pull_request_target` I guess.
