### ISSUE TITLE
CSI driver: optimized image populator with estargz

### ISSUE THREAD

**Issue by imjasonh** [imjasonh/ideas#89]
https://kubernetes.io/blog/2020/01/21/csi-ephemeral-inline-volumes/#image-populator-https-github-com-kubernetes-csi-csi-driver-image-populator
https://github.com/kubernetes-csi/csi-driver-image-populator
https://github.com/containerd/stargz-snapshotter/blob/v0.2.0/docs/stargz-estargz.md

**Comment by imjasonh** [comment]
Instead of:

```yaml
containers:
- image: my-app:latest
```

It would be:

```yaml
containers:
- image: scratch  # or something small
volumes:
  - name: blah
    csi:
      driver: my.magic.driver
      volumeAttributes:
        image: my-app:latest
```

_(maybe mutated by a webhook!)_

And then the driver could pull paths on-demand from `my-app:latest` if it's estargz-enabled. If it's not, the driver could pull the whole image, but then also estargz-optimize it and push it to a registry for future pulls.

The driver would need to support read-write in case the image writes stuff.
