### ISSUE TITLE
Octant plugin to view/managed cached images

### ISSUE THREAD

**Issue by imjasonh** [imjasonh/ideas#92]
List k8s node objects, and `.status.images` includes [information about images cached on the node](https://pkg.go.dev/k8s.io/api/core/v1#ContainerImage), including refs and total image size:

<details><summary>example YAML</summary>
```yaml
  images:
  - names:
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:720ba70dc20f6bb3672ce696fbeb58ca1b005fcd96acdeacaa2dbaf75bbc9a50
    sizeBytes: 40937177
  - names:
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller@sha256:e6e92621e4192768fd5f189b5c10724c652bbcc2565f225ebca1c73fb9f52f58
    sizeBytes: 38194292
  - names:
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook@sha256:244815c2daecc8ee60c27a8df9947fe67d0c7b9f52e809de450bdccb32c8dd75
    sizeBytes: 35503070
  - names:
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:599e95ac34de374a34cb93a25b7f653714bd17824d8c0f7260036a7ba0a9bc30
    sizeBytes: 30192946
  - names:
    - gcr.io/kaniko-project/executor@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5
    - gcr.io/kaniko-project/executor:v1.5.1
    sizeBytes: 28355622
```
</details>

Show what images/digests are available across the fleet, which nodes are closest to hitting the [eviction threshold](https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/), and maybe try to find some way to proactively selectively evict images to free up space (knowing that other layers that other images on the node might share would _not_ be evicted).

- https://reference.octant.dev/?path=/docs/docs-plugins-1-getting-started--page
